//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public admin_account()
        {
            this.admin_baivietlienhe = new HashSet<admin_baivietlienhe>();
            this.admin_gioithieu = new HashSet<admin_gioithieu>();
            this.admin_hanhtrinh = new HashSet<admin_hanhtrinh>();
            this.admin_hinhanh = new HashSet<admin_hinhanh>();
            this.admin_loaihanhtrinh = new HashSet<admin_loaihanhtrinh>();
            this.admin_loaihinhanh = new HashSet<admin_loaihinhanh>();
            this.admin_loaitintuc = new HashSet<admin_loaitintuc>();
            this.admin_nhomthanhvien = new HashSet<admin_nhomthanhvien>();
            this.admin_thanhvien = new HashSet<admin_thanhvien>();
            this.admin_tintuc = new HashSet<admin_tintuc>();
            this.banners = new HashSet<banner>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public Nullable<System.DateTime> landangnhapcuoi { get; set; }
        public string hoten { get; set; }
        public Nullable<bool> gioitinh { get; set; }
        public string ghichu { get; set; }
        public Nullable<int> quyen { get; set; }
        public Nullable<bool> daxoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_baivietlienhe> admin_baivietlienhe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_gioithieu> admin_gioithieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hanhtrinh> admin_hanhtrinh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_hinhanh> admin_hinhanh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_loaihanhtrinh> admin_loaihanhtrinh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_loaihinhanh> admin_loaihinhanh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_loaitintuc> admin_loaitintuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_nhomthanhvien> admin_nhomthanhvien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_thanhvien> admin_thanhvien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_tintuc> admin_tintuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<banner> banners { get; set; }
    }
}
