//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_hanhtrinh
    {
        public int id { get; set; }
        public string tenhanhtrinh { get; set; }
        public Nullable<int> loaihanhtrinh { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public Nullable<System.DateTime> ngaycapnhat { get; set; }
        public string motasoluoc { get; set; }
        public string noidung { get; set; }
        public Nullable<bool> hienthi { get; set; }
        public Nullable<int> nguoitao { get; set; }
        public Nullable<bool> daxoa { get; set; }
        public string ghichu { get; set; }
        public string thongtinthoigian { get; set; }
        public string thongtindiadiem { get; set; }
        public string hinhdaidien { get; set; }
        public string tenhanhtrinh_en { get; set; }
        public string motasoluoc_en { get; set; }
        public string noidung_en { get; set; }
        public string diadiem_en { get; set; }
    
        public virtual admin_account admin_account { get; set; }
        public virtual admin_loaihanhtrinh admin_loaihanhtrinh { get; set; }
    }
}
