//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_thongtincodinh
    {
        public int id { get; set; }
        public string diachi { get; set; }
        public string dienthoai { get; set; }
        public string website { get; set; }
        public string fax { get; set; }
        public string mail { get; set; }
        public string logo { get; set; }
        public string diachigmap { get; set; }
        public string baiviettrangchu { get; set; }
        public string diachi_en { get; set; }
        public string baiviettrangchu_en { get; set; }
    }
}
