//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class banner
    {
        public int id { get; set; }
        public string tenbanner { get; set; }
        public string urlbanner { get; set; }
        public string motabanner { get; set; }
        public string ghichu { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public Nullable<System.DateTime> ngaycapnhat { get; set; }
        public Nullable<int> nguoitao { get; set; }
        public Nullable<bool> hienthi { get; set; }
        public Nullable<int> thutuhien { get; set; }
        public Nullable<bool> daxoa { get; set; }
        public Nullable<int> loaibanner { get; set; }
    
        public virtual admin_account admin_account { get; set; }
        public virtual loaibanner loaibanner1 { get; set; }
    }
}
