//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Areas.Admin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebApplication1Entities1 : DbContext
    {
        public WebApplication1Entities1()
            : base("name=WebApplication1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_account> admin_account { get; set; }
        public virtual DbSet<admin_baivietlienhe> admin_baivietlienhe { get; set; }
        public virtual DbSet<admin_gioithieu> admin_gioithieu { get; set; }
        public virtual DbSet<admin_hanhtrinh> admin_hanhtrinh { get; set; }
        public virtual DbSet<admin_hinhanh> admin_hinhanh { get; set; }
        public virtual DbSet<admin_loaihanhtrinh> admin_loaihanhtrinh { get; set; }
        public virtual DbSet<admin_loaihinhanh> admin_loaihinhanh { get; set; }
        public virtual DbSet<admin_loaitintuc> admin_loaitintuc { get; set; }
        public virtual DbSet<admin_nhomthanhvien> admin_nhomthanhvien { get; set; }
        public virtual DbSet<admin_thanhvien> admin_thanhvien { get; set; }
        public virtual DbSet<admin_thongtincodinh> admin_thongtincodinh { get; set; }
        public virtual DbSet<admin_tintuc> admin_tintuc { get; set; }
        public virtual DbSet<banner> banners { get; set; }
        public virtual DbSet<loaibanner> loaibanners { get; set; }
    }
}
